// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1gQtfFl1qBCminAXk3UtsAPzr85MKr_4',
    appId: '1:789821995496:web:e593e203bf99c33a64cc5d',
    messagingSenderId: '789821995496',
    projectId: 'notes-p2p-flutter',
    authDomain: 'notes-p2p-flutter.firebaseapp.com',
    storageBucket: 'notes-p2p-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOdiSM7ZXW6QNmFDj2q612-1L5fTSmpnc',
    appId: '1:789821995496:android:eb24d6adc186d93d64cc5d',
    messagingSenderId: '789821995496',
    projectId: 'notes-p2p-flutter',
    storageBucket: 'notes-p2p-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALNJ3D1uq0zgX_jlMYEvydXZJi6L1OQeE',
    appId: '1:789821995496:ios:bc6de8d07823a84764cc5d',
    messagingSenderId: '789821995496',
    projectId: 'notes-p2p-flutter',
    storageBucket: 'notes-p2p-flutter.appspot.com',
    androidClientId: '789821995496-97gsf8dj6tu4n1dukrac4ihscp3tog5j.apps.googleusercontent.com',
    iosClientId: '789821995496-4vipu6ipr9haradd3fd2kg607g6du8vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALNJ3D1uq0zgX_jlMYEvydXZJi6L1OQeE',
    appId: '1:789821995496:ios:b6641de91562a20964cc5d',
    messagingSenderId: '789821995496',
    projectId: 'notes-p2p-flutter',
    storageBucket: 'notes-p2p-flutter.appspot.com',
    androidClientId: '789821995496-97gsf8dj6tu4n1dukrac4ihscp3tog5j.apps.googleusercontent.com',
    iosClientId: '789821995496-t55dgp04e350t4kbbaf685p1oin4v20v.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp.RunnerTests',
  );
}
